[workspace]

members = [ "test-lib", "testA", "testB", "testC" ]

[workspace.dependencies]
nalgebra = "0.32.4"
serde = { version = "1.0.197", features = ["derive"] }
test-lib = { path = "test-lib", version = "0.1.0" }