[package]
name = "testB"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.4"
serde = { version = "1.0.197", features = ["derive"] }
test-lib = { path = "../test-lib", version = "0.1.0" }
